### PR TITLE
ELasticsearch single node for developers and basics

### PR DESCRIPTION
**Pull request by jinnabaalu**
- Elasticsearch as a single node cluster for dev machine
- Basic commands used in elasticsearch
- Crud operations for developer

### CODE REVIEW

**Comment by marcosnils** [comment]
This is very nice @JinnaBalu . Thx for submitting cc @pmckeetx

**Comment by jinnabaalu** [comment]
Hi @marcosnils thanks, Do we have an option to test before it goes live.

**Comment by marcosnils** [comment]
@JinnaBalu yes, you can start this repo locally and try the local in your local machine. There's instructions on how to accomplish this on the README

**Comment by jinnabaalu** [comment]
I am familiar with Jekyll but do we get the terminal to test

**Comment by jinnabaalu** [comment]
When can we expect this PR to be merged ?

**Pull request closed without merging**
