### PR TITLE
Correction looping on querySelectorAll because not working on firefox…

### PR DESCRIPTION
**Pull request by allamand**
source for the fix : https://css-tricks.com/snippets/javascript/loop-queryselectorall-matches/

### CODE REVIEW

**Comment by marcosnils** [comment]
@allamand thx for the catch. I guess i'd prefer to use a classic loop as you've used the approach that seems "hacky". Mind crafting a PR to change it that way?

**Comment by allamand** [comment]
No pb but tomorrow I'm out for today ;)

Sébastien

**Comment by marcosnils** [comment]
sure, thx!

**Comment by allamand** [comment]
@marcosnils, I proposed a version with classic loop. it still works for me ;)

**Pull request merged**
