### PR TITLE
add orchestration workshop

### PR DESCRIPTION
**Pull request by jpetazzo**
⚠️  I didn't find an easy way to preview my changes so I'd appreciate if somebody could check that I did things correctly before merging this. Thanks!

### CODE REVIEW

**Comment by marcosnils** [comment]
hey @jpetazzo the README has an instruction about how to spin a jekyll container to view your changes locally. That didn't work for you?

**Comment by marcosnils** [comment]
@jpetazzo can you please add `terms: 0` to the post header?. That will make the page not to show any terminals on the bday site.

**Comment by jpetazzo** [comment]
Ah, I feel silly, I tried to display it with my Jekyll build (the one I use for my blog) and it didn't work; I didn't see the README. :man_facepalming: :man_facepalming: :man_facepalming: 

- added `terms: 0`
- fixed display order
- shortened titles to avoid breaking the layout

✔️  ready to go!

**Comment by marcosnils** [comment]
:tada:

**Pull request merged**
