### PR TITLE
Add Application Containerization and Microservice Orchestration tutorial

### PR DESCRIPTION
**Pull request by ibnesayeed**
This is an exhaustive tutorial covering from basic script containerization to gradually evolve into a multi-service application.

### CODE REVIEW

**Comment by marcosnils** [comment]
@ibnesayeed just checked the interactive and everything works perfectly. I'll wait for @ManoMarks review before merging.

**Comment by chanezon** [comment]
Thank you @ibnesayeed this is a very nice tutorial. I have a few comments about the Docker best practices in the codebase in the repo https://github.com/ibnesayeed/linkextractor (Dockerfiles, versions, env variables) instead of the tutorial itself, but nothing blocking.
I'd say let's merge it today, then please make corrections to both codebase and tutorial based on this discussion.

https://github.com/ibnesayeed/linkextractor/blob/master/step1/Dockerfile
There should be a tag for the from image, example python:2.7

Instead of 2 pip install lines, better have a requirements.txt file and run pip on it once, so that it's one layer.
```
COPY requirements.txt /
RUN pip install -r /requirements.txt
```
But I see that you do that later, so maybe it's OK to start with 2 pip commands. Maybe then explain when you move from 2 pip lines to a requirements file that this creates only one layer.

https://github.com/ibnesayeed/linkextractor/blob/step5/api/main.py#L10
Nice to have.
it's weird to have API_ENDPOINT being an env variable in thew compose file, then hardcoding the redis host to the service name in compose file.
https://github.com/ibnesayeed/linkextractor/blob/step5/docker-compose.yml
Maybe parametrize both. 

web:php and api:python, php and python are strange tags. usually you tag services with a version number. I get it that then you replace python with ruby. Maybe do v1python and v2ruby, and v1php for the web version.

same remark as above for step6 Dockerfile, Ruby from image should have a specific version
https://github.com/ibnesayeed/linkextractor/blob/step6/api/Dockerfile

**Comment by marcosnils** [comment]
Thx @chanezon for reviewing. @ibnesayeed feel free to open further PR's to address Patrick's comments. 

Amazing work!.

**Comment by ibnesayeed** [comment]
Thanks for the review and kind words @chanezon and @marcosnils. I have made changes in the demo code and created a new PR #160 to reflect those changes that should take care of your concerns (I am open for further changes).

Here are my reflections on your feedback:

In practice, I try to follow the Dockerfile best practices almost religiously, as much as I can and often fix Dockerfiles in random repos on GitHub. However, in this tutorial, I was intentionally trying to avoid some of those to illustrate certain points and to avoid the need of explaining certain things even before I got my readers comfortable with basics. A good example of that would be the use repeated `pip install` commands to illustrate more clearly how one would discover missing dependencies and install it one by one if the dependency file was not provided (I could have used `pip install package1 package2 ...` syntax too, but that would kill the purpose). The theme of the lesson is to starts with a simple script and demonstrate how painful it might be to run something as simple as that, and then gradually improve it in steps to finally evolve it into a multi-service application.

I used `API_ENDPOINT` environment variable to make it configurable because I was later planning to swap the API service with the Ruby implementation and illustrate how one might supply changes from outside. However, I had no plans to change anything about Redis in either implementations so I didn't parametrize it as I thought it would add more noise and confusion (and more text to explain while the point was already made). That said, now I have made it configurable as well.

Regarding `web:php`, `api:python`, and `api:ruby` tags, I don't think image tags are necessarily versions, they can be variations in some cases. For example, in the official images when we say `python:alpine`, we are not talking about a version, but a variation of the same version of the Python that is available in other forms and bases as well. I was trying to use shorter, but descriptive enough names here. However, I have now changed them to something like `linkextractor-api:step6-ruby`.

As far as tagging base images (those in the `FROM` directives) is concerned, I agree that it is a *good practice* to use specific images as it guarantees that the code will not start failing due to changes in upstream dependencies, but it certainly is not mandatory, and I often prefer to start with less restrictions and clutter when I am teaching Docker or anything for that matter. That said, I have now added first point version number tags to every base image.

**Pull request merged**
