### PR TITLE
Step not clear in Swarm stack introduction

### PR DESCRIPTION
**Pull request by neomatrix369**
Added notes to ensure that the user in the first terminal when typing the command, to resolve any doubt the end-user might have. Related to and fixes issue #68

### CODE REVIEW

**Comment by marcosnils** [comment]
NACK. If you can click on the code block and it'll get executed on the terminal automatically I think this is not necessary @xetorthio ?

**Comment by neomatrix369** [comment]
@marcosnils I wasn't aware of this functionality, nothing on the instructions says it. If you agree, I can add a note on clicking on the code block of the rest to happen.

But people might choose to type the code block(s), for e.g typing leads to better remembering and understanding of the lessons and hence this might be necessary for those concerned.

I only did this, since I made a mistake the first time over and had to restart the window to redo the exercise.

**Comment by neomatrix369** [comment]
@marcosnils We could add this note:
```
Important note: in the labs, when you see a command inside some grey rectangle, you just need to click on it so it is executed in the terminal (but if you want you can also write it manually into the terminal).
```

Which is present in the next session.

**Comment by neomatrix369** [comment]
Fixes #68

**Pull request merged**
