### PR TITLE
Bricks Tutorials for MongoDB ReplicaSet/Cluster & Redis Replication/Cluster

### PR DESCRIPTION
**Pull request by athakwani**
Bricks allow building any container stack without service discovery. Complex stacks like MongoDB Cluster can be built with few simple commands. More information is available @ https://github.com/pipecloud/bricks

### CODE REVIEW

**Comment by athakwani** [comment]
Hi @marcosnils @ManoMarks,

Could you please check these tutorials and let me know if they can be merged?

**Comment by ManoMarks** [comment]
We're going to discuss this PR at a meeting next week among other things.

**Comment by athakwani** [comment]
Thanks for the update.

**Review by ManoMarks — CHANGES_REQUESTED** [review]
In the jeykll front matter in each of these, change the categories key from advanced to  community. This is a new category we're going to use to replace "others".

Also please add a 2-3 sentences at the start of each of these labs explaining what bricks is and why someone might want to use it in this context.

**Comment by athakwani** [comment]
Hi @ManoMarks I have made the requested changes. Please review.

**Review by ManoMarks — APPROVED** [review]

**Pull request merged**
