### PR TITLE
Fix link of the web interface of Link Extractor.

### PR DESCRIPTION
**Pull request by hoangnam2261**
Hi there,
Just fix link of the web interface of Link Extractor.
 Thanks,

### CODE REVIEW

**Comment by marcosnils** [comment]
This is not correct.

**Comment by hoangnam2261** [comment]
Hi @marcosnils,
Can you help me explain more detailed about why it's not correct?
As a reader, i read tutorial on this page https://training.play-with-docker.com/microservice-orchestration/#step-4-link-extractor-api-and-web-front-end-services when i click on the link, it point back to this link https://training.play-with-docker.com/, it very confusing to me and everyone.

**Comment by marcosnils** [comment]
> As a reader, i read tutorial on this page https://training.play-with-docker.com/microservice-orchestration/#step-4-link-extractor-api-and-web-front-end-services when i click on the link, it point back to this link https://training.play-with-docker.com/, it very confusing to me and everyone.

Are you pressing ctrl + click or something when clicking the link? What it should happen if you just left click on the link is that it should open a tab and point it to the deployed application which you configured in the terminal. It's not intended to point to `localhost` stuff

**Comment by hoangnam2261** [comment]
Ok @marcosnils,
The last question, did you have any try to click the link on the page i sent before you comment?
Thanks,

**Comment by marcosnils** [comment]
> The last question, did you have any try to click the link on the page i sent before you comment?
> Thanks,

Yes, and it works for me as intended. If it's not working for you maybe you can record a quick GIF to see what's happening and send your browser and OS version?

**Pull request closed without merging**
