### PR TITLE
Update 2017-06-26-docker-networking-hol.markdown

### PR DESCRIPTION
**Pull request by aak74**
correct domain name is docker.com

### CODE REVIEW

**Review by marcosnils — COMMENTED** [review]
Hmm so think docker.com can't be pinged so I guess sñwe should use GitHub everywhere

**Comment by aak74** [comment]
then we probably should replace www.docker.com to www.github.com in this context

Lets ping **www.github.com** by running `ping -c5 www.github.com`
```.term1
  ping -c5 www.github.com
```

**Comment by marcosnils** [comment]
Yes, that's what I was my suggestion. Mind updating the PR?

**Comment by aak74** [comment]
sure

**Pull request merged**
