### PR TITLE
Add labs

### PR DESCRIPTION
**Pull request by lucj**
Add labs for techwhale lessons 2/3/4/5:
- containers
- images
- registry
- volumes

### CODE REVIEW

**Comment by marcosnils** [comment]
@lucj nice!. Would you mind adding the `docker` tag as well so they get displayed correctly in the `index` page?

**Comment by lucj** [comment]
No problem. Do you want I use special names instead of "lessons" ?

**Comment by allamand** [comment]
Cool ;) thanks

**Comment by marcosnils** [comment]
> Do you want I use special names instead of "lessons" ?

If it's not too much trouble. 

Things like docker-images, docker-containers, docker-registry, etc would be better IMHO.

**Comment by lucj** [comment]
no problem at all

**Comment by marcosnils** [comment]
:tada: thx a lot @lucj !

**Comment by lucj** [comment]
I'm glad I can help.
BTW, I'll need to find better pics for each one :)

**Comment by marcosnils** [comment]
> I'll need to find better pics for each one :)

I was taking care of that :)

**Pull request merged**
